services:
   ffc-sfd-file-receiver: 
    build:
      context: .
      target: production
    image: ffc-sfd-file-receiver
    container_name: ffc-sfd-file-receiver
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-file-receiver-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      DATA_HOST: ${DATA_HOST:-http://ffc-sfd-data:3004/graphql}
      MESSAGE_HOST: ${MESSAGE_HOST}
      MESSAGE_USER: ${MESSAGE_USER}
      MESSAGE_PASSWORD: ${MESSAGE_PASSWORD}
      FILE_RECEIVER_TOPIC_ADDRESS: ${FILE_RECEIVER_TOPIC_ADDRESS}-${DEV_SUFFIX}
      FILE_RECEIVER_SUBSCRIPTION_ADDRESS: ${FILE_RECEIVER_SUBSCRIPTION_ADDRESS}-${DEV_SUFFIX}