# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfd-file-receiver:
    build:
      target: development
    image: ffc-sfd-file-receiver-development
    container_name: ffc-sfd-file-receiver-development
    ports:
      - "3020:3020"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
      
